load("@rules_cc//cc:defs.bzl", "cc_binary")

# Build rule for creating an executable (target).
cc_binary(
    name = "test-all-vehicles",
    srcs = ["src/main.cpp"],    
    deps = ["//libs:AllVehicles"],
)